// <auto-generated />
using DataModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataModels.Migrations
{
    [DbContext(typeof(LibraryAppDbContext))]
    [Migration("20191023131756_Init99")]
    partial class Init99
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataModels.BookDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Context");

                    b.Property<int>("Genre");

                    b.Property<string>("Image");

                    b.Property<int>("NumbersOfCopies");

                    b.Property<string>("Title");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Books");

                    b.HasData(
                        new { Id = 1, Author = "Annie Auerbach", Context = @"SpongeBob's ego--and head--swell when he is selected to  
                    star in a television special as the world's biggest daredevil,  
                    but hotshot producer Barry Cuda has another role in mind for him.", Genre = 6, Image = "https://images-na.ssl-images-amazon.com/images/I/51aF2mEeDrL._SX341_BO1,204,203,200_.jpg", NumbersOfCopies = 10, Title = "SpongeBob Superstar", UserId = 1 },
                        new { Id = 2, Author = "Clive Cussler", Context = @"Marine explorer Dirk Pitt must rely on the nautical lore
                    of Jules Verne to stop a ruthless oil baron with his sights set on political
                    power in this #1 New York Times-bestselling series.", Genre = 5, Image = "https://images-na.ssl-images-amazon.com/images/I/81LXwqs6eiL.jpg", NumbersOfCopies = 8, Title = "Valhalla rising", UserId = 1 }
                    );
                });

            modelBuilder.Entity("DataModels.UserDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, FirstName = "Bob", LastName = "Bobsky", Password = "(?\\?-??3#>L?q", Username = "bob007" }
                    );
                });

            modelBuilder.Entity("DataModels.BookDTO", b =>
                {
                    b.HasOne("DataModels.UserDTO", "User")
                        .WithMany("BookList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
